name: Check JSON Tag and Notify Discord

on:
  schedule:
    - cron: '0 * * * *' # Run the job every hour (adjust as needed)
  workflow_dispatch:

jobs:
  check_tag:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Fetch JSON Response
      run: |
        curl -s "https://product-details.mozilla.org/1.0/firefox_versions.json" > response.json

    - name: Read JSON Tag
      id: json
      run: |
        VALUE=$(jq -r '.LATEST_FIREFOX_RELEASED_DEVEL_VERSION' response.json)
        echo "VALUE=$VALUE" >> $GITHUB_ENV

    - name: Compare Tag
      id: compare
      run: |
        if [ "${{ env.VALUE }}" != "134.0b11" ]; then
          echo "different=true" >> $GITHUB_ENV
        else
          echo "different=false" >> $GITHUB_ENV
        fi

    - name: Send Discord Webhook
      if: env.different == 'true'
      run: |
        curl -H "Content-Type: application/json" -X POST -d '{"content":"The LATEST_FIREFOX_RELEASED_DEVEL_VERSION has changed to: ${{ env.VALUE }}"}' ${{ secrets.DISCORD_WEBHOOK_URL }}
